language: node_js

node_js:
  - 8

install:
  - npm install -g firebase-tools
  - firebase setup:emulators:firestore
  - npm install

script:
  - firebase \
    emulators:exec \
    --only firestore \
    "npm run test"

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master