language: node_js
node_js:
  - 8

install:
  - npm install -g firebase-tools
  - npm install

before_script:
  - firebase setup:emulators:firestore

script:
  - npm run firestore-test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master