language: node_js
node_js:
  - 8
env:
  - FIRESTORE_EMULATOR_HOST=localhost:8080

install:
  - npm install
  - npm install -g firebase-tools
  - firebase setup:emulators:firestore  

script:
  - npm run serve-test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master