language: node_js
node_js:
  - 8

install:
  - npm install

# before_script:
#   - firebase setup:emulators:firestore

script:
  - firebase \
    emulators:exec \
    --only firestore \
    "npm run test"

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master