language: node_js
node_js:
  - 8
  - 10

install:
  - npm install
  - npm install -g firebase-tools

before_script:
  - npm run db:clear

script:
  - npm test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master